steps:
  - name: node:16
    id: 'Install dependencies'
    entrypoint: npm
    args: [ 'install' ]
  - name: node:16
    id: 'Run unit tests'
    waitFor: [ 'Install dependencies' ]
    entrypoint: npm
    args: [ 'test' ]
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [ 'Install dependencies', 'Run unit tests' ]
    id: 'Bake Image'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cms-api:latest', '-t', 'gcr.io/$PROJECT_ID/cms-api:$COMMIT_SHA' ,'.' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image to the Registry'
    waitFor: [ 'Install dependencies', 'Run unit tests', 'Bake Image' ]
    args: [ 'push', 'gcr.io/$PROJECT_ID/cms-api' ]
  - id: 'Deploy to k8s'
    timeout: 900s
    waitFor: [ 'Push Image to the Registry' ]
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=k8s/
      - --image=gcr.io/$PROJECT_ID/cms-api:latest
      - --location=us-central1-c
      - --cluster=cms-k8s-cluster
options:
  logging: GCS_ONLY
timeout: 2400s
