apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  selector:
    matchLabels:
      app: cms-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cms-api
        tier: cms-api
    spec:
      containers:
        - name: cms-api
          image: docker2022cms/cms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: cms-api

---
apiVersion: v1
kind: Service
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  type: LoadBalancer
  selector:
    app: cms-api
    tier: cms-api
  ports:
    - port: 3000
      targetPort: 3000
