apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  progressDeadlineSeconds: 1200
  replicas: 1
  selector:
    matchLabels:
      app: cms-api
  strategy:
    type: Recreate
  minReadySeconds: 90
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      containers:
        - name: cms-api
          image: gcr.io/course-management-system-api/cms-api:latest
          timeoutSeconds: 600
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: POSTGRES_DATABASE
              value: course-management
            - name: REDIS_PREFIX
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: REDIS_PREFIX
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: REDIS_PORT
            - name: CACHE_TTL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: CACHE_TTL
            - name: REDIS_VOLUME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: REDIS_VOLUME
            - name: PREFIX_PATH
              value: "api"
            - name: SYNCHRONIZE
              value: "false"
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PRIVATE_KEY
            - name: AUTH_TOKEN_EXPIRED_TIME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: AUTH_TOKEN_EXPIRED_TIME
            - name: IS_EMAIL_ENABLED
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: IS_EMAIL_ENABLED
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MAIL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_SERVICE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MAIL_SERVICE
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: PROJECT_ID
            - name: GCP_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: GCP_PRIVATE_KEY
            - name: CLIENT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: CLIENT_EMAIL
            - name: HW_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: HW_BUCKET
            - name: FILE_SIZE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: FILE_SIZE
            - name: FILES_QTY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: FILES_QTY
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.31.1
          command:
            - "/cloud_sql_proxy"
            - "-instances=course-management-system-api:us-central1:cms-api-db-1=tcp:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
